name: Manual Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment a deploy'
        required: true
        default: 'production'

jobs:
  manual_job:
  runs-on: ubuntu-latest
    steps:
    - name: 
      run: |
env: NOM_VARIABLE: valeur

